package com.everis.notificaciones.model;
// Generated 27/09/2019 12:58:19 PM by Hibernate Tools 5.2.12.Final



import static javax.persistence.GenerationType.IDENTITY;


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;


/**
 * Cliente generated by hbm2java
 */
	@Entity
	@Table(name = "cliente", catalog = "examen3")
	public class Cliente implements java.io.Serializable {

		/**
		 * 
		 */
		private static final long serialVersionUID = 1L;
		private int id;
		private String nombre;
		private String latitud;
		private String longitud;

		public Cliente() {
		}

		public Cliente(int id) {
			this.id = id;
		}

		
		@Id
		@GeneratedValue(strategy = IDENTITY)
		@Column(name = "id", unique = true, nullable = false)
		public int getId() {
			return this.id;
		}

		public void setId(int id) {
			this.id = id;
		}

		@Column(name = "nombre", length = 45)
		public String getNombre() {
			return this.nombre;
		}

		public void setNombre(String nombre) {
			this.nombre = nombre;
		}

		@Column(name = "latitud", length = 45)
		public String getLatitud() {
			return this.latitud;
		}

		public void setLatitud(String latitud) {
			this.latitud = latitud;
		}

		@Column(name = "longitud", length = 45)
		public String getLongitud() {
			return this.longitud;
		}

		public void setLongitud(String longitud) {
			this.longitud = longitud;
		}


	}
