package com.everis.notificaciones.model;
// Generated 27/09/2019 12:58:19 PM by Hibernate Tools 5.2.12.Final



import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pedido generated by hbm2java
 */

public class Pedido implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private Cliente cliente;
	private Date fechahoraregistro;
	private Date fechahoraentrega;
	private Set<Producto> productos = new HashSet<Producto>(0);

	public Pedido() {
	}

	public Pedido(int id, Cliente cliente) {
		this.id = id;
		this.cliente = cliente;
	}

	public Pedido(int id, Cliente cliente, Date fechahoraregistro, Date fechahoraentrega, Set<Producto> productos) {
		this.id = id;
		this.cliente = cliente;
		this.fechahoraregistro = fechahoraregistro;
		this.fechahoraentrega = fechahoraentrega;
		this.productos = productos;
	}


	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}


	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}


	public Date getFechahoraregistro() {
		return this.fechahoraregistro;
	}

	public void setFechahoraregistro(Date fechahoraregistro) {
		this.fechahoraregistro = fechahoraregistro;
	}


	public Date getFechahoraentrega() {
		return this.fechahoraentrega;
	}

	public void setFechahoraentrega(Date fechahoraentrega) {
		this.fechahoraentrega = fechahoraentrega;
	}


	public Set<Producto> getProductos() {
		return this.productos;
	}

	public void setProductos(Set<Producto> productos) {
		this.productos = productos;
	}

}
