package com.everis.notificaciones.model;
// Generated 27/09/2019 12:58:19 PM by Hibernate Tools 5.2.12.Final



import java.util.HashSet;
import java.util.Set;


import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Producto generated by hbm2java
 */

public class Producto implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private String nombre;
	private Double precio;
	private String url;
	@JsonIgnore
	private Set<Pedido> pedidos = new HashSet<Pedido>(0);

	public Producto() {
	}

	public Producto(int id) {
		this.id = id;
	}

	public Producto(int id, String nombre, Double precio, String url, Set<Pedido> pedidos) {
		this.id = id;
		this.nombre = nombre;
		this.precio = precio;
		this.url = url;
		this.pedidos = pedidos;
	}

	
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}


	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	
	public Double getPrecio() {
		return this.precio;
	}

	public void setPrecio(Double precio) {
		this.precio = precio;
	}


	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}


	public Set<Pedido> getPedidos() {
		return this.pedidos;
	}

	public void setPedidos(Set<Pedido> pedidos) {
		this.pedidos = pedidos;
	}

}
